#! /bin/sh

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config window_gap 0
bspc config border_width        1

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc query -M | xargs -i{} bspc monitor {} -d 1 2 3 e r t y u i o

MONITORS=($(bspc query -M))
MTAIL=${MONITORS[@]:(-1)}
bspc config -m $MTAIL top_padding 16
if [[ "${MONITORS[0]}" != "$MTAIL" ]]; then
    bspc config -m ${MONITORS[0]} top_padding 0
fi
bspc config bottom_padding 16

# Autostart
sxhkd &

export PATH=$HOME/languages/go/bin:$PATH

if uname -v | grep -q "NixOS"; then
    FONTDIR="/run/current-system/sw/share/X11-fonts"
else
    FONTDIR="/usr/share/fonts/TTF"
fi

osop -c bsp.toml 2>/tmp/osop1| gobar --bottom --fg=0xff8e8e8e --bg=0xff383a3b --fonts=$FONTDIR/LiberationMono-Regular.ttf:11 &
