#! /bin/sh

bspc config window_gap 0
bspc config border_width        1

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc query -M | xargs -i{} bspc monitor {} -d 1 2 3 e r t y u i o

#bspc rule -a Gimp desktop=^8 follow=on floating=on
#bspc rule -a Chromium desktop=^2
#bspc rule -a Screenkey manage=off
bspc config -m $(bspc query -M | tail -1) top_padding 16
bspc config bottom_padding 16
